DROP TABLE IF EXISTS orderItems CASCADE;
CREATE TABLE orderItems (
  id SERIAL PRIMARY KEY NOT NULL,
  order_id INTEGER REFERENCES orders(id) ON DELETE CASCADE,
  menuItem_id INTEGER REFERENCES menuItems(id) ON DELETE CASCADE
);
